using System;
using System.Xml.Linq;
using iDeal.Base;

namespace iDeal.Transaction
{
    public class TransactionRequest : iDealRequest
    {
        private string _merchantReturnUrl;
        private string _purchaseId;
        private TimeSpan? _expirationPeriod;
        private string _description;
        private string _entranceCode;

        /// <summary>
        /// Unique identifier of issuer
        /// </summary>
        public string IssuerId { get; private set; }

        /// <summary>
        /// Url to which consumer is redirected after authorizing the payment
        /// </summary>
        public string MerchantReturnUrl
        {
            get
            {
                return _merchantReturnUrl;
            }
            set
            {
                if (string.IsNullOrWhiteSpace(value))
                    throw new InvalidOperationException("Merchant url is required");
                _merchantReturnUrl = value.Trim();
            }
        }

        /// <summary>
        /// Unique id determined by the acceptant, which will eventuelly show on the bank account
        /// </summary>
        public string PurchaseId
        {
            get { return _purchaseId; }
            set
            {
                if (string.IsNullOrWhiteSpace(value))
                    throw new InvalidOperationException("Purchase id is required");
                if (value.Length > 16)
                    throw new InvalidOperationException("Purchase id cannot contain more than 16 characters");
                _purchaseId = value;
            }
        }

        /// <summary>
        /// Amount measured in cents
        /// </summary>
        public int Amount { get; private set; }

        /// <summary>
        /// Time until consumer has to have paid, otherwise the transaction is marked as expired by the issuer (consumer's bank)
        /// </summary>
        public TimeSpan? ExpirationPeriod
        {
            get { return _expirationPeriod; }
            set
            {
                if (value.HasValue)
                {
                    if (value.Value.TotalMinutes < 1)
                        throw new InvalidOperationException("Minimum expiration period is one minute");
                    if (value.Value.TotalMinutes > 60)
                        throw new InvalidOperationException("Maximum expiration period is 1 hour");
                }
                _expirationPeriod = value;
            }
        }

        /// <summary>
        /// Description ordered product (no html tags!)
        /// </summary>
        public string Description
        {
            get { return _description; }
            set
            {
                if (value.Trim().Length > 32)
                    throw new InvalidOperationException("Description cannot contain more than 32 characters");
                _description = value.Trim();
            }
        }

        /// <summary>
        /// Unique code generated by acceptant by which consumer can be identified
        /// </summary>
        public string EntranceCode
        {
            get { return _entranceCode; }
            set
            {
                if (string.IsNullOrWhiteSpace(value))
                    throw new InvalidOperationException("Entrance code is required");
                if (value.Length > 40)
                    throw new InvalidOperationException("Entrance code cannot contain more than 40 characters");
                _entranceCode = value;
            }
        }
        public TransactionRequest(string merchantId, int? subId, string issuerId, string merchantReturnUrl, string purchaseId, int amount, TimeSpan? expirationPeriod, string description, string entranceCode)
            : base(merchantId, subId)
        {
            IssuerId = issuerId;
            MerchantReturnUrl = merchantReturnUrl;
            PurchaseId = purchaseId;
            Amount = amount;
            ExpirationPeriod = expirationPeriod ?? TimeSpan.FromMinutes(30); // Default 30 minutes expiration
            Description = description;
            EntranceCode = entranceCode;
        }

        protected override XDocument CreateXml()
        {
            return new XDocument(
                    new XDeclaration("1.0", "UTF-8", null),
                    new XElement(XmlNamespace + "AcquirerTrxReq",
                        new XAttribute("version", "3.3.1"),
                        new XElement(XmlNamespace + "createDateTimestamp", createDateTimestamp),
                        new XElement(XmlNamespace + "Issuer",
                            new XElement(XmlNamespace + "issuerID", IssuerId.ToString().PadLeft(4, '0'))
                        ),
                        new XElement(XmlNamespace + "Merchant",
                            new XElement(XmlNamespace + "merchantID", MerchantId.PadLeft(9, '0')),
                            new XElement(XmlNamespace + "subID", "0"),
                            new XElement(XmlNamespace + "merchantReturnURL", MerchantReturnUrl)
                        ),
                        new XElement(XmlNamespace + "Transaction",
                            new XElement(XmlNamespace + "purchaseID", PurchaseId),
                            new XElement(XmlNamespace + "amount", Amount),
                            new XElement(XmlNamespace + "currency", "EUR"),
                            new XElement(XmlNamespace + "expirationPeriod", "PT" + Convert.ToInt32(Math.Floor(ExpirationPeriod.Value.TotalSeconds)) + "S"),
                            new XElement(XmlNamespace + "language", "nl"),
                            new XElement(XmlNamespace + "description", Description),
                            new XElement(XmlNamespace + "entranceCode", EntranceCode)
                        )
                    )
                );
        }
    }
}
