using System.Xml.Linq;
using iDeal.Base;

namespace iDeal.Transaction
{
    public class TransactionResponse : iDealResponse
    {
        /// <summary>
        /// Url of issuer to which the customer has to be redirected
        /// </summary>
        public string IssuerAuthenticationUrl { get; private set; }

        /// <summary>
        /// Acquirer id (first four digits) + unique id generated by acquirer (last 12 digits)
        /// </summary>
        public string TransactionId { get; private set; }

        /// <summary>
        /// Datetime when the transaction was first registered by the Acquirer
        /// </summary>
        public string TransactionCreateDateTimestamp { get; private set; }

        /// <summary>
        /// Unique id determined by the acceptant, which will eventuelly show on the bank account
        /// </summary>
        public string PurchaseId { get; private set; }

        public TransactionResponse(XElement xDocument)
            : base(xDocument)
        {
            IssuerAuthenticationUrl = xDocument.Element(XmlNamespace + "Issuer").Element(XmlNamespace + "issuerAuthenticationURL").Value;
            TransactionId = xDocument.Element(XmlNamespace + "Transaction").Element(XmlNamespace + "transactionID").Value;
            TransactionId = xDocument.Element(XmlNamespace + "Transaction").Element(XmlNamespace + "transactionID").Value;
            TransactionCreateDateTimestamp = xDocument.Element(XmlNamespace + "Transaction").Element(XmlNamespace + "transactionCreateDateTimestamp").Value;
            PurchaseId = xDocument.Element(XmlNamespace + "Transaction").Element(XmlNamespace + "purchaseID").Value;
        }
    }
}
